#!/bin/bash

function usage() {
	echo "usage: $0 [checkout | status | update | pull | push] <option>"
	echo "  options:"
	echo "    -f force push or force clean checkout"
	exit 1
}

cd "$(dirname $0)"

FORCE=
if [ "$2" = "-f" ]; then
	FORCE=-f
fi

base_dirs="workdir backup ssl configs"

case $1 in
	status)
		for dir in $base_dirs; do
			echo "#######################################"
			echo "######## $dir"
			echo "#######################################"
			(cd $dir && git status)
		done
		for dir in workdir/*/Dockerfile; do
			CONTAINER=$(dirname $dir)
			BRANCH=$(basename $CONTAINER)
			echo "#######################################"
			echo "#### $CONTAINER/config"
			echo "#######################################"
			(cd $CONTAINER/config && git status)
		done
	;;
	push)
		DIFF=$(cd workdir && git diff HEAD..origin/docker | wc -l)
		if [ $DIFF -ne 0 ]; then
			(cd workdir && git push $FORCE origin docker:docker)
		fi
		DIFF=$(cd configs && git diff HEAD..origin/configs | wc -l)
		if [ $DIFF -ne 0 ]; then
			(cd configs && git push $FORCE origin configs:configs)
		fi
		DIFF=$(cd ssl && git diff HEAD..origin/ssl | wc -l)
		if [ $DIFF -ne 0 ]; then
			(cd ssl && git push $FORCE origin ssl:ssl)
		fi
		DIFF=$(cd backup && git diff HEAD..origin/backup | wc -l)
		if [ $DIFF -ne 0 ]; then
			(cd backup && git push $FORCE origin backup:backup)
		fi
		for dir in workdir/*/Dockerfile; do
			CONTAINER=$(dirname $dir)
			BRANCH=$(basename $CONTAINER)
			DIFF=$(cd $CONTAINER/config && git diff HEAD..origin/$BRANCH | wc -l)
			if [ $DIFF -ne 0 ]; then
				(cd $CONTAINER/config && git push $FORCE origin $BRANCH:$BRANCH)
			fi
		done
	;;
	checkout | update | pull)
		REPO=$(git remote get-url origin 2> /dev/null || git remote show origin | grep Fetch | cut -d" " -f5)
		[ -n "$FORCE" -a "$1" = "checkout" ] && rm -rf workdir backup
		if [ -d workdir ]; then
			(cd workdir && git pull --rebase)
		else
			git clone --branch docker $REPO workdir
		fi
		if [ -d configs ]; then
			(cd configs && git pull --rebase)
		else
			git clone --branch configs $REPO configs
		fi
		if [ -d ssl ]; then
			(cd ssl && git pull --rebase)
		else
			git clone --branch ssl $REPO ssl
		fi
		if [ -d backup ]; then
			(cd backup && git pull --rebase)
		else
			git clone --branch backup $REPO backup
		fi
		for dir in workdir/*/Dockerfile; do
			CONTAINER=$(dirname $dir)
			BRANCH=$(basename $CONTAINER)
			if [ -d $CONTAINER/config ]; then
				(cd $CONTAINER/config && git pull --rebase)
			else
				git clone --branch $BRANCH $REPO $CONTAINER/config
			fi
		done
	;;
	help)
		usage
	;;
	*)
		echo "unknown command: $1"
		usage
	;;
esac
